# Generated by Django 4.2.30 on 2026-08-28 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_code', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('imei', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMEI (Móviles)')),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Computador Portátil'), ('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet'), ('MONITOR', 'Monitor'), ('PRINTER', 'Impresora'), ('PERIPHERAL', 'Periférico'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Activo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('BODEGA', 'En Bodega'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='BODEGA', max_length=20, verbose_name='Estado')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de Adquisición')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidences/assets/', verbose_name='Foto de Evidencia Física')),
            ],
            options={
                'verbose_name': 'Activo TI',
                'verbose_name_plural': 'Activos TI',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='ID de Empleado / Cédula')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Institucional')),
                ('role', models.CharField(max_length=100, verbose_name='Rol / Cargo')),
                ('department', models.CharField(max_length=100, verbose_name='Área / Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('details', models.TextField(verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('check_out_notes', models.TextField(verbose_name='Notas de Entrega')),
                ('check_out_accessories', models.JSONField(default=list, verbose_name='Accesorios Entregados')),
                ('check_out_image', models.ImageField(blank=True, null=True, upload_to='evidences/checkouts/', verbose_name='Foto de Evidencia Entrega')),
                ('check_in_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('check_in_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Devolución')),
                ('check_in_accessories', models.JSONField(blank=True, default=list, null=True, verbose_name='Accesorios Recibidos')),
                ('check_in_image', models.ImageField(blank=True, null=True, upload_to='evidences/checkins/', verbose_name='Foto de Evidencia Recepción')),
                ('pdf_acta', models.FileField(blank=True, null=True, upload_to='actas/', verbose_name='Acta de Responsabilidad (PDF)')),
                ('signature_pdf', models.FileField(blank=True, null=True, upload_to='signatures/', verbose_name='Acta Firmada (PDF)')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Devuelto')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventario.activoti', verbose_name='Activo TI')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventario.personal', verbose_name='Empleado')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_handled', to=settings.AUTH_USER_MODEL, verbose_name='Analista de TI')),
            ],
            options={
                'verbose_name': 'Asignación / Préstamo',
                'verbose_name_plural': 'Asignaciones / Préstamos',
            },
        ),
    ]
